# src/config.py

DATA_PATH = "data.csv"

# Global Config
EXPENSE_COLS = [
    'Rent', 'Loan_Repayment', 'Insurance', 'Groceries', 'Transport',
    'Eating_Out', 'Entertainment', 'Utilities', 'Healthcare', 
    'Education', 'Miscellaneous'
]
WEEKLY_WEIGHTS = {'W1': 0.27, 'W2': 0.25, 'W3': 0.25, 'W4': 0.23}
NUM_COLS = ['Income', 'Age', 'Dependents'] + EXPENSE_COLS # Simplified for brevity
CAT_COLS = ['Occupation', 'City_Tier']

# --- TASK 1: Overspend Classification Features ---
# From Cell 49
FEATURES_OVERSPEND = [
    'Income', 'Age', 'Dependents', 'Occupationencoded', 'City_Tierencoded',
    # Weekly columns generated by FeatureEngineer
    'Rent_W1','Rent_W2','Rent_W3','Rent_W4',
    'Groceries_W1', 'Groceries_W2', 'Groceries_W3', 'Groceries_W4' 
    # (Add all other weekly columns as per notebook)
]
TARGET_OVERSPEND = 'Overspend'

# --- TASK 2: Actual Savings Regression Features ---
# From Cell 57
FEATURES_SAVINGS = FEATURES_OVERSPEND # Seems to share same inputs
TARGET_SAVINGS = 'Actual_Savings'

# --- TASK 3: Financial Health Classification Features ---
# From Cell 66
FEATURES_HEALTH = [
    'Total_Expenses',
    'Weekly_Overspend_Trend', # Note: Ensure this is created in processing
    'Disposable_Income',
    'Spending_Trend',
    'Savings_Efficiency'
]
TARGET_HEALTH = 'Financial_Health'

# --- TASK 4: Suggesting Savings Features ---
# From Cell 79
FEATURES_SUGGESTIONS = [
    "Income","Age","Dependents","Occupationencoded","City_Tierencoded",
    "Disposable_Income","Desired_Savings","Savings_Efficiency",
    "Spending_Trend", "Overspend",
    "Weekly_Savings_W1", "Weekly_Savings_W2", "Weekly_Savings_W3", "Weekly_Savings_W4"
]
TARGETS_SUGGESTIONS = [
    "Potential_Savings_Groceries", "Potential_Savings_Transport",
    "Potential_Savings_Eating_Out", "Potential_Savings_Entertainment",
    "Potential_Savings_Utilities", "Potential_Savings_Healthcare",
    "Potential_Savings_Education", "Potential_Savings_Miscellaneous"
]